version: "2.1"
services:
  user_service:
    container_name: user_service
    build:
      context: ./user_service
    ports:
      - "7083:7082"
    environment:
      - DEBUG=True
  post_service:
    container_name: post_service
    build:
      context: ./post_service
    ports:
      - "7084:7082"
    environment:
      - DEBUG=True
  comment_service:
    container_name: comment_service
    build:
      context: ./comment_service
    ports:
      - "7085:7082"
    environment:
      - DEBUG=True
  server:
    container_name: server
    build:
      context: ./server
    ports:
      - "7082:7082"
    environment:
      - DEBUG=True
    # Uncomment this when code is ready for production
#  front_end:
#    container_name: front_end
#    build:
#      context: .
#      dockerfile: ./src/Dockerfile
#    ports:
#      - "7081:7081"
#    environment:
#      - DEBUG=True